config/routes.rb
OW::Application.routes.draw do
  resources :service_apres_ventes

  match "/email_box/:id"=>'email_box#show'
  match "/email_box"=>'email_box#index'
  match "/email_box/:id/destroy"=>'email_box#destroy'

  resources :project_actions

  resources :message_boxes do
    resources:comments
  end

  resources :invoices
  match "/invoices/:invoice_id/payments/new"=>'invoices#new_payment' ,:as=>:new_payments
   match "/invoices/:invoice_id/payments/create"=>'invoices#create_payment' ,:as=>:payments
  match "/payments/:payment_id"=>'invoices#destroy_payment',:as=>:payments_destroy
   match '/invoices/:id/facture',:to=>'invoices#create_facture' ,:as=>:facture
  resources :documents

  get "search/new_search"
  get "search/search_options",:as =>:search_options
  get "search/search_result"
  match "search/:model_id/test"=>"search#test"
  match "supports/custom_mail"=>"supports#custom_mail", :as=>:custom_mail
  match "supports/custom_mail_200"=>"supports#custom_mail_200", :as=>:custom_mail_200
  match "supports/send_custom_mail"=>"supports#send_custom_mail", :as=>:send_custom_mail
  match "supports/send_custom_mail_200"=>"supports#send_custom_mail_200", :as=>:send_custom_mail_200
  resources :supports

  resources :comments

  resources :projects do
    resources :invoices
    resources :project_actions

    
  end
  match "project_actions/:id/success_failure"=>"project_actions#success_or_failure", :as=>:success_failure

  root :to => 'home_page#home'

  get "home_page/home"
   get "home_page/test"

  resources :clients do
    resources :projects
  end
  match "message_box/:id/delete_trashed_comments"=>"message_boxes#trashed_comments" ,:as=>:delete_trashed_comments
  match "message_box/:id/archive_comments"=>"message_boxes#archived_comments" ,:as=>:archive_yml_comments
  match "/comments/:id/salvage"=>"comments#salvage_comment",:as=>:salvage_comment
  match "/comments/:id/restore"=>"comments#restore_comment",:as=>:restore_comment
  match "/comments/:id/read"=>"comments#read_comment",:as=>:read_comment
  match "/comments/:id/archive"=>"comments#archive_comment",:as=>:archive_comment
  match "/comments/:id/trash"=>"comments#trash_comment",:as=>:trash_comment
  match "/comments/:id/respond"=>"comments#respond_to_comment",:as=>:respond_comment
  match "/projects/:id/activate_project"=>"projects#activate_project",:as=>:activate_project

  match "/users/:id/activate_user"=>"users#activate_user",:as=>:activate_user
  match "/users/:id/admin"=>"users#admin_user_on_off",:as=>:admin_user
  match "/users/:id/deactivated"=>"users#de_re_activate_user",:as=>:deactivate_user
   match "/users/smtp_settings"=>"users#set_smtp_account_settings",:as=>:set_smtp_account_settings
  match "/users/save_smtp_settings"=>"users#save_smtp_account_settings",:as=>:save_smtp_account_settings
  match "/projects/:id/close_project"=>"projects#close_project",:as=>:close_project
  match "/projects/:id/lost_project"=>"projects#lost_project",:as=>:lost_project
  match "/projects/:id/activate_project"=>"projects#activate_project",:as=>:activate_project
  match "/clients/:id/change_state"=>"clients#change_state",:as=>:client_change_state

  match "/current_user_projects"=>'projects#current_user_projects',:as =>:current_user_projects
  match "/current_user_clients"=>'clients#current_user_clients',:as =>:current_user_clients
  match "/user_clients/:user_id"=>'clients#user_clients',:as =>:user_clients

  get "sessions/new"

  match "files/upload", :to =>'files#upload' ,:as =>'upload_files'
  match "files/post_upload", :to =>'files#post_upload' ,:as =>'post_upload'
  get "files/index"

  get "users/show"
  match "/service_apres_vente/:id/activate_sav"=>"service_apres_ventes#activate_sav",:as=>:activate_sav
  match "/service_apres_vente/:id/close_sav"=>"service_apres_ventes#close_sav",:as=>:close_sav
  match "service_apres_ventes_active", :to =>'service_apres_ventes#index_active' ,:as =>'index_active'
  match "service_apres_ventes_closed", :to =>'service_apres_ventes#index_closed' ,:as =>'index_closed'
  match "service_apres_ventes_sent", :to =>'service_apres_ventes#index_sent' ,:as =>'index_sent'
  match "service_apres_ventes_warranty", :to =>'service_apres_ventes#index_warranty' ,:as =>'index_warranty'
  match "service_apres_ventes_no_warranty", :to =>'service_apres_ventes#index_no_warranty' ,:as =>'index_no_warranty'
  match "service_apres_ventes_planned", :to =>'service_apres_ventes#index_planned' ,:as =>'index_planned'
  match "service_apres_ventes_unplanned", :to =>'service_apres_ventes#index_unplanned' ,:as =>'index_unplanned'
  match "service_apres_ventes/:id/send_form", :to =>'service_apres_ventes#send_sav_form_mail' ,:as =>'send_sav_form_mail'
  match "service_apres_ventes/:id/sav_fiche", :to =>'service_apres_ventes#create_sav_fiche' ,:as =>'create_sav_fiche'
  match 'user_upload', :to => 'users#upload_a_file'
  match 'project_upload', :to => 'projects#upload_a_file'

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/redirect', :to =>'application#redirect_to_last_visited'

  match '/projects/:id/fiche_de_rendez_vous',:to=>'projects#create_rendez_vous_fiche' ,:as=>:fiche_de_rendez_vous
  match '/projects/:id/fiche_de_rendez_vous_mail',:to=>'projects#send_fiche_de_rendez_vous_mail' ,:as=>:fiche_de_rendez_vous_mail
  match '/projects/:id/SAV_form' ,:to=>'projects#send_sav_form_mail',:as=>:send_SAV_form_mail
  match '/project/:id/follow',:to=>'projects#follow_project',:as=>:follow_project
  match '/project/:id/assign',:to=>'projects#assign_project',:as=>:assign_project
  match '/project/:id/project_price',:to=>'projects#set_project_price',:as=>:set_project_price

  resources :user_profiles
  resources :users do
    resource :user_profiles # a verifier

  end

  post "files/post_upload"
  match 'files/download' =>'files#download'

  resources :files
  resources :sessions, :only => [:new, :create, :destroy]
  match '/file_browser/pieces_jointes' => 'file_browser#list_for_piece_jointe', :as => :piece_jointes
   match '/file_browser/set_pieces_jointes' => 'file_browser#set_piece_jointe', :as => :set_piece_jointes
  match '/file_browser' => 'file_browser#list', :as => :file_browser
  match '/user_files' => 'file_browser#user_files', :as => :user_files
   match '/projects/:project_id/project_files' => 'file_browser#project_files', :as => :project_files
  match '/projects/:project_id/file_browser/file/create'  => 'file_browser#create_file',  :as => :create_project_file_file_browser
  match '/file_browser/delete' => 'file_browser#delete', :as => :delete_file_file_browser
  match '/file_browser/dir/create'  => 'file_browser#create_dir',  :as => :create_dir_file_browser
  match '/file_browser/file/create'  => 'file_browser#create_file',  :as => :create_file_file_browser
  match '/file_browser/archive'  => 'file_browser#list_for_archive',  :as => :file_browser_archive
  match '/file_browser/retrieve_archive'  => 'file_browser#retrieve_archive',  :as => :file_browser_retrieve_archive

  get "welcome/index"
  resources :supports, :only => [:new, :create]

end

app/views/shared/_address_fields_without_description.erb
<fieldset>


  <%= f.label :street,'Rue' %><br>
  <%= f.text_field :street%><br>
  <%= f.label :street_number ,'N°'%><br>
  <%= f.text_field :street_number %><br>
  <%= f.label :floor,'Etage' %><br>
  <%= f.text_field :floor %><br>
  <%= f.label :zip,'Code postal' %><br>
  <%= f.text_field :zip %><br>
  <%= f.label :city,'Ville/Commune' %><br>
  <%= f.text_field :city%><br>
  <%= f.label :country, 'Pays' %><br>
  <%= f.text_field :country %><br>
  

</fieldset>

app/views/shared/_address_show.erb
<div class="span-16 box">
<div class='span-15'>
<h4><b><%=address.description%></b></h4></div>

<div class="span-4">
 <b>Rue    : </b><%=address.street%><br/>
 <b>Code postal: </b><%=address.zip%>
</div>
<div class='span-4'>
  <b>Numero : </b><%=address.street_number%><br/>
  <b>Ville : </b><%=address.city%>
</div>
<div class="span-3">
<b>Etage  :</b><%= address.floor %><br/>
<b>Pays : </b><%=address.country%>
</div>
<div class='span-4'>
<%=link_to_external address.format_url_for_google_maps,"Trouver sur Google-Maps"%>
 <%=link_to_external address.format_url_for_mappy_maps,"Trouver sur Mappy"%></div>
</div>

 <%#link_to_external address.format_url_for_mappy_itinerary("Bruxelles,+1050,+rue du sceptre,+85,+belgique"),"Trouver sur Mappy"%>

app/views/shared/_contact_fields.html.erb
<div class="fields">
  <fieldset>
    
    <%= f.label :description %><br>
    <%= f.text_field :description %><br>
    <%= f.label :genre,'Type de contact: ' %><br>
    <%= f.select :genre, get_contact_type  %><br>
    <%= f.label :contact_data,'Donnée du Contact' %><br>
    <%= f.text_field :contact_data %><br>
    <%= link_to_remove_fields "Effacer Contact", f %>
  </fieldset>

</div>    

app/views/shared/_contact_list.erb
<tr>
<td>
<%= contact.description %></td>
  <td>
<%= contact.genre %></td>
  <td>
<%= contact.contact_data %></td>
</tr>

app/views/shared/_contact_show.erb
<div class= "span-16 box">
<p><b>Description       : </b><%= contact.description %></p>
<div class="span-4">
  <p><b>Type de Contact   : </b><%= contact.genre %>
</div>
<div class="span-6">
<b>Donnée du Contact : </b><%= contact.contact_data %>
</div>
</div>

app/views/shared/_financial_datum_fields.html.erb
<fieldset>

  <%= f.label :tva_number ,'Numero de TVA'%><br>
  <%= f.text_field :tva_number %><br>
  <%= f.label :tva_rate,'Taux de TVA'%><br>
  <%= f.text_field :tva_rate %><br>
  <%= f.label :bank_account,'N° de compte en banque' %><br>
  <%= f.text_field :bank_account %><br>


</fieldset>

app/views/shared/_flash.erb
<div id="flash" style="min-height: 50px" >


<% flash.each do |key, msg| %>
    <%= content_tag :div, msg, :class => [key, " message"], :id => "notice_#{key}" %>
     <% content_tag :script, :type => "text/javascript" do %>
     $('#<%="notice_#{key}" %>').fadeOut(5000);
  <% end %>
<% end %>

</div>

app/views/shared/_not_signed.erb
<div id="sign_in_status" class="span-4 ">
  <p>Vous n'êtes pas enregistré... </p>

   <%= link_to 'Connectez-vous' , signin_path(:format =>:js),:remote=>true%>
</div>

app/views/shared/_project_component_fields.html.erb
<div class="fields">
<fieldset>
  <%= f.label :component_type,'Type de Produit: ' %><br>
  <%= f.select :component_type, get_component_type  %><br>
  <%= f.label :component_matter,'Matière: ' %><br>
   <%= f.select :component_matter, get_component_matter  %><br>
  <%= f.label :number_of_component,'Nombre de pièces' %><br>
  <%= f.text_field :number_of_component %><br>
  <%= f.label :component_info,'Informations supplémentaires' %><br>
  <%= f.text_field :component_info %><br>
  <%= link_to_remove_fields "Effacer Composant", f %>
</fieldset>
</div>

app/views/shared/_search_options.erb
<br />
<div class="span-11" id="search_page">

<div id='searchoption'>
<% if params[:model_type].nil? %>
<div class="valign span-4">  Rechercher un ? &nbsp</div>
<div class="span-5">
<%= select_tag :model_type ,
               options_for_select(model_list
                )%>
</div>
<%else%>
  <%= hidden_field_tag :model_type ,params[:model_type] %>
  <%=link_for_model_options_search params[:model_type] %>
 <%end%>

<div id="client">
<div class="valign span-4">
Type de Client:
</div>
<div class="span-4">
  <%= select_tag :client_type ,
               options_for_select(client_type
                )%>
</div>
<div class="valign span-4">
Etat du Client:
</div>
<div class="span-4">
  <%= select_tag :client_state ,
               options_for_select(client_state
                )%>
</div>
</div>
<div id="project">
<div class="valign span-4">  Type de Projet:</div>
<div class="span-4">  <%= select_tag :project_type ,
               options_for_select(project_type
                )%></div>
<div class="valign span-4">Etat du Projet:</div>
  <div class="span-4"> <%= select_tag :project_state ,
               options_for_select(project_state
                )%></div>

</div>

<div id="uploadedfiles">

</div>
<div id="address">

</div>
<div id='contact'>
<div class="valign span-4">
  Type de Contact:</div>
  <div class="span-4">

<%= select_tag :contact_type ,
               options_for_select(contact_type
                )%>
</div>
</div>

<div id="time">
<div class="valign span-4">
 Rechercher un modele:
</div>
 <div class=" span-4" id="time_type">
 <%= select_tag :time_type ,
               options_for_select(time_type
                )%>
 </div>
<div class="valign span-4">
 il y a moins de
</div>
<div class=" span-4">
<%= select_tag :time_number, options_for_select(1..30
                )%>
<%= select_tag :time ,
               options_for_select(created
                )%>
</div>
 <div class='valign span-2'>
<%=link_to_function('Cacher','$("#time").hide(); $("#time").children().attr("disabled", true);  $("#optiontemps").show();$("#time_opt:hidden").val(0);')%>
</div>


</div>
<div id="general">
<div class="valign span-4">Résultats par pages:</div><div class=" span-4 "> <%= select_tag :per_page ,
               options_for_select(per_page_result
                )%></div>
  <div class='valign span-2'>
<%=link_to_function('Cacher','$("#general").hide(); $("#general").children().attr("disabled", true);  $("#optiongeneral").show();$("#gen_opt:hidden").val(0);')%>
</div>
</div>

</div>
</div>

app/views/shared/_signed.erb
<div id="sign_in_status" class="span-4  ">
  <p>Connecté en tant que:  <%=current_user.name %> </p>
  <%= link_to 'se déconnecter' ,:controller =>'sessions' ,:action =>'destroy' %>
</div>