config/routes.rb
OW::Application.routes.draw do
  resources :service_apres_ventes

  match "/email_box/:id"=>'email_box#show'
  match "/email_box"=>'email_box#index'
  match "/email_box/:id/destroy"=>'email_box#destroy'

  resources :project_actions

  resources :message_boxes do
    resources:comments
  end

  resources :invoices
  match "/invoices/:invoice_id/payments/new"=>'invoices#new_payment' ,:as=>:new_payments
   match "/invoices/:invoice_id/payments/create"=>'invoices#create_payment' ,:as=>:payments
  match "/payments/:payment_id"=>'invoices#destroy_payment',:as=>:payments_destroy
   match '/invoices/:id/facture',:to=>'invoices#create_facture' ,:as=>:facture
  resources :documents

  get "search/new_search"
  get "search/search_options",:as =>:search_options
  get "search/search_result"
  match "search/:model_id/test"=>"search#test"
  match "supports/custom_mail"=>"supports#custom_mail", :as=>:custom_mail
  match "supports/custom_mail_200"=>"supports#custom_mail_200", :as=>:custom_mail_200
  match "supports/send_custom_mail"=>"supports#send_custom_mail", :as=>:send_custom_mail
  match "supports/send_custom_mail_200"=>"supports#send_custom_mail_200", :as=>:send_custom_mail_200
  resources :supports

  resources :comments

  resources :projects do
    resources :invoices
    resources :project_actions

    
  end
  match "project_actions/:id/success_failure"=>"project_actions#success_or_failure", :as=>:success_failure

  root :to => 'home_page#home'

  get "home_page/home"
   get "home_page/test"

  resources :clients do
    resources :projects
  end
  match "message_box/:id/delete_trashed_comments"=>"message_boxes#trashed_comments" ,:as=>:delete_trashed_comments
  match "message_box/:id/archive_comments"=>"message_boxes#archived_comments" ,:as=>:archive_yml_comments
  match "/comments/:id/salvage"=>"comments#salvage_comment",:as=>:salvage_comment
  match "/comments/:id/restore"=>"comments#restore_comment",:as=>:restore_comment
  match "/comments/:id/read"=>"comments#read_comment",:as=>:read_comment
  match "/comments/:id/archive"=>"comments#archive_comment",:as=>:archive_comment
  match "/comments/:id/trash"=>"comments#trash_comment",:as=>:trash_comment
  match "/comments/:id/respond"=>"comments#respond_to_comment",:as=>:respond_comment
  match "/projects/:id/activate_project"=>"projects#activate_project",:as=>:activate_project

  match "/users/:id/activate_user"=>"users#activate_user",:as=>:activate_user
  match "/users/:id/admin"=>"users#admin_user_on_off",:as=>:admin_user
  match "/users/:id/deactivated"=>"users#de_re_activate_user",:as=>:deactivate_user
   match "/users/smtp_settings"=>"users#set_smtp_account_settings",:as=>:set_smtp_account_settings
  match "/users/save_smtp_settings"=>"users#save_smtp_account_settings",:as=>:save_smtp_account_settings
  match "/projects/:id/close_project"=>"projects#close_project",:as=>:close_project
  match "/projects/:id/lost_project"=>"projects#lost_project",:as=>:lost_project
  match "/projects/:id/activate_project"=>"projects#activate_project",:as=>:activate_project
  match "/clients/:id/change_state"=>"clients#change_state",:as=>:client_change_state

  match "/current_user_projects"=>'projects#current_user_projects',:as =>:current_user_projects
  match "/current_user_clients"=>'clients#current_user_clients',:as =>:current_user_clients
  match "/user_clients/:user_id"=>'clients#user_clients',:as =>:user_clients

  get "sessions/new"

  match "files/upload", :to =>'files#upload' ,:as =>'upload_files'
  match "files/post_upload", :to =>'files#post_upload' ,:as =>'post_upload'
  get "files/index"

  get "users/show"
  match "/service_apres_vente/:id/activate_sav"=>"service_apres_ventes#activate_sav",:as=>:activate_sav
  match "/service_apres_vente/:id/close_sav"=>"service_apres_ventes#close_sav",:as=>:close_sav
  match "service_apres_ventes_active", :to =>'service_apres_ventes#index_active' ,:as =>'index_active'
  match "service_apres_ventes_closed", :to =>'service_apres_ventes#index_closed' ,:as =>'index_closed'
  match "service_apres_ventes_sent", :to =>'service_apres_ventes#index_sent' ,:as =>'index_sent'
  match "service_apres_ventes_warranty", :to =>'service_apres_ventes#index_warranty' ,:as =>'index_warranty'
  match "service_apres_ventes_no_warranty", :to =>'service_apres_ventes#index_no_warranty' ,:as =>'index_no_warranty'
  match "service_apres_ventes_planned", :to =>'service_apres_ventes#index_planned' ,:as =>'index_planned'
  match "service_apres_ventes_unplanned", :to =>'service_apres_ventes#index_unplanned' ,:as =>'index_unplanned'
  match "service_apres_ventes/:id/send_form", :to =>'service_apres_ventes#send_sav_form_mail' ,:as =>'send_sav_form_mail'
  match "service_apres_ventes/:id/sav_fiche", :to =>'service_apres_ventes#create_sav_fiche' ,:as =>'create_sav_fiche'
  match 'user_upload', :to => 'users#upload_a_file'
  match 'project_upload', :to => 'projects#upload_a_file'

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/redirect', :to =>'application#redirect_to_last_visited'

  match '/projects/:id/fiche_de_rendez_vous',:to=>'projects#create_rendez_vous_fiche' ,:as=>:fiche_de_rendez_vous
  match '/projects/:id/fiche_de_rendez_vous_mail',:to=>'projects#send_fiche_de_rendez_vous_mail' ,:as=>:fiche_de_rendez_vous_mail
  match '/projects/:id/SAV_form' ,:to=>'projects#send_sav_form_mail',:as=>:send_SAV_form_mail
  match '/project/:id/follow',:to=>'projects#follow_project',:as=>:follow_project
  match '/project/:id/assign',:to=>'projects#assign_project',:as=>:assign_project
  match '/project/:id/project_price',:to=>'projects#set_project_price',:as=>:set_project_price

  resources :user_profiles
  resources :users do
    resource :user_profiles # a verifier

  end

  post "files/post_upload"
  match 'files/download' =>'files#download'

  resources :files
  resources :sessions, :only => [:new, :create, :destroy]
  match '/file_browser/pieces_jointes' => 'file_browser#list_for_piece_jointe', :as => :piece_jointes
   match '/file_browser/set_pieces_jointes' => 'file_browser#set_piece_jointe', :as => :set_piece_jointes
  match '/file_browser' => 'file_browser#list', :as => :file_browser
  match '/user_files' => 'file_browser#user_files', :as => :user_files
   match '/projects/:project_id/project_files' => 'file_browser#project_files', :as => :project_files
  match '/projects/:project_id/file_browser/file/create'  => 'file_browser#create_file',  :as => :create_project_file_file_browser
  match '/file_browser/delete' => 'file_browser#delete', :as => :delete_file_file_browser
  match '/file_browser/dir/create'  => 'file_browser#create_dir',  :as => :create_dir_file_browser
  match '/file_browser/file/create'  => 'file_browser#create_file',  :as => :create_file_file_browser
  match '/file_browser/archive'  => 'file_browser#list_for_archive',  :as => :file_browser_archive
  match '/file_browser/retrieve_archive'  => 'file_browser#retrieve_archive',  :as => :file_browser_retrieve_archive

  get "welcome/index"
  resources :supports, :only => [:new, :create]

end

app/controllers/file_browser_controller.rb
class FileBrowserController < ApplicationController
  before_filter :authenticate
  before_filter :define_path
  def list_for_archive
    session[:model_id]=nil
    session[:model]=nil
    define_archive
    list=UploadedFile.list(@current_path,@public_path,@current_url)
    @dirs=list[:dir]
    @files=list[:file]
    @breadcrumb=list[:breadcrumb]
  end


  def retrieve_archive
    @comments=UploadedFile.retrieve_archive(params[:archive_url])
    
  end
  def list_for_piece_jointe
    session[:model_id]=nil
    session[:model]=nil
    list=UploadedFile.list(@current_path,@public_path,@current_url)
    @dirs=list[:dir]
    @files=list[:file]
    @breadcrumb=list[:breadcrumb]
  end
  def set_piece_jointe
    session[:piece_jointe_url]=params[:piece_jointe_url]
    session[:piece_jointe_name]=params[:piece_jointe_name]
    redirect_to custom_mail_path
  end
  def list
    session[:model_id]=nil
    session[:model]=nil
    list=UploadedFile.list(@current_path,@public_path,@current_url)
    @dirs=list[:dir]
    @files=list[:file]
    @breadcrumb=list[:breadcrumb]
  end

  def user_files
    session[:model]=current_user.class
    session[:model_id]=current_user.id
    define_root(current_user)
    list=UploadedFile.list(@current_path,@public_path,@current_url)
    @dirs=list[:dir]
    @files=list[:file]
    @breadcrumb=list[:breadcrumb]
   
  end
   def project_files
    @project=Project.find(params[:project_id])
    session[:model]=@project.class
    session[:model_id]=@project.id
    define_root(@project)
    list=UploadedFile.list(@current_path,@public_path,@current_url)
    @dirs=list[:dir]
    @files=list[:file]
    @breadcrumb=list[:breadcrumb]

  end
  def create_dir
    notice=UploadedFile.create_directory(params[:new_dir],@public_path)
    redirect_to request.referer, :notice => notice
  end


  def create_file
    if session[:model].nil?
      model=current_user
    else
      model=session[:model].find(session[:model_id])
    end

    notice=UploadedFile.create_file(params['post_upload'],@public_path,model)
    redirect_to request.referer, :notice => notice
  end

  def delete
    #file=UploadedFile.find_by_path(params[:file])
    file=UploadedFile.find_by_path(File.join(@public_path,params[:file]))
    if file!=nil
      file.destroy
      notice=file.path+" "
    else
      notice='if it is not a dir it is an error '
    end

    notice=notice+UploadedFile.delete(params[:file],@public_path)
    redirect_to request.referer, :notice => notice
  end
end
 

app/helpers/file_browser_helper.rb
module FileBrowserHelper


end

app/views/file_browser/__breadcrumb.html.erb
<ul id="breadcrumb">
  <% @breadcrumb.each do |crumb| %>

      <li>/<a href="<%= url_for file_browser_path :dir => crumb[:url] %>" title="Go to '<%= crumb[:name] %>' folder"><%= crumb[:name] %></a></li>
      
  <% end %>
</ul>

app/views/file_browser/__file_browser_content.html.erb
<div id='file_browser_content'>
  <ul class="directories"style="height:0px;padding:0;margin:0">
    <% @dirs.each do |dir| %>
        <li class="dir">
          <div class="icon">
            <a href="<%= url_for file_browser_path :dir => dir[:url] %>">
              <label><%= dir[:name] %></label>
            </a>
          </div>
          <ul class="infos">
            <li class="label"><label><%= dir[:name] %></label></li>
            <li class="delete"><a href="<%= url_for delete_file_file_browser_path :file => dir[:url] %>">delete</a></li>
          </ul>
        </li>
    <% end %>
  </ul>

  <ul class="files"style="height:0px;padding:0;margin:0">
    <% @files.each do |file| %>
        <li class="<%= file[:type] %>">
          <div class="icon">
            <a href="<%= file[:url] %>"><img src="<%= file[:icon] %>" title="<%= file[:name] %>" /></a>
          </div>
          <ul class="infos">
            <li class="label"><label title="<%= file[:name] %>"><%= file[:name] %></label></li>
            <li class="delete"><a href="<%= url_for delete_file_file_browser_path :file => file[:url] %>" title="Delete this file">delete</a></li>
          </ul>
        </li>
    <% end %>
  </ul>
</div>

app/views/file_browser/__p_j_breadcrumb.html.erb
<ul id="breadcrumb">
  <% @breadcrumb.each do |crumb| %>

      <li>/<a href="<%= url_for piece_jointes_path :dir => crumb[:url] %>" title="Go to '<%= crumb[:name] %>' folder"><%= crumb[:name] %></a></li>

  <% end %>
</ul>

app/views/file_browser/_archive_content.html.erb
<%@comments unless @comments.nil?%>
<div id='file_browser_content'>
  <ul class="directories"style="height:0px;padding:0;margin:0">
    <% @dirs.each do |dir| %>
        <li class="dir">
          <div class="icon">
            <a href="<%= url_for file_browser_path :dir => dir[:url] %>">
              <label><%= dir[:name] %></label>
            </a>
          </div>
          <ul class="infos">
            <li class="label"><label><%= dir[:name] %></label></li>
            <li class="delete"><a href="<%= url_for delete_file_file_browser_path :file => dir[:url] %>">delete</a></li>
          </ul>
        </li>
    <% end %>
  </ul>

  <ul class="files"style="height:0px;padding:0;margin:0">
    <% @files.each do |file| %>
        <li class="<%= file[:type] %>">
          <div class="icon">
            <a href="<%= url_for file_browser_retrieve_archive_path :archive_url=>file[:url] %>"><img src="<%= file[:icon] %>" title="<%= file[:name] %>" /></a>
          </div>
          <ul class="infos">
            <li class="label"><label title="<%= file[:name] %>"><%= file[:name] %></label></li>
            <li class="delete"><a href="<%= url_for delete_file_file_browser_path :file => file[:url] %>" title="Delete this file">delete</a></li>
          </ul>
        </li>
    <% end %>
  </ul>
</div>

app/views/file_browser/_create_directory_form.html.erb
<div id="create_directory_input" style="display: none">
<%= form_tag  create_dir_file_browser_path ,:id=>"new_dir" do%>
  <input type="hidden" name="new_dir[path]" value="<%= @current_url %>" />
  <h2>Créer un dossier</h2>
  <%=label 'new_dir' , 'Directory name' %>
  <%= text_field 'new_dir', 'name' %>
  <%= submit_tag "Create" %>
<% end%>
</div>

app/views/file_browser/_piece_jointe_content.html.erb
<div id='file_browser_content'>
  <ul class="directories"style="height:0px;padding:0;margin:0">
    <% @dirs.each do |dir| %>
        <li class="dir">
          <div class="icon">
            <a href="<%= url_for piece_jointes_path :dir => dir[:url] %>">
              <label><%= dir[:name] %></label>
            </a>
          </div>
          <ul class="infos">
            <li class="label"><label><%= dir[:name] %></label></li>
            <li class="delete"><a href="<%= url_for delete_file_file_browser_path :file => dir[:url] %>">delete</a></li>
          </ul>
        </li>
    <% end %>
  </ul>

  <ul class="files"style="height:0px;padding:0;margin:0">
    <% @files.each do |file| %>
        <li class="<%= file[:type] %>">
          <div class="icon">
            <a href="<%= url_for set_piece_jointes_path :piece_jointe_name=> file[:name],:piece_jointe_url=>file[:url] %>"><img src="<%= file[:icon] %>" title="<%= file[:name] %>" /></a>
          </div>
          <ul class="infos">
            <li class="label"><label title="<%= file[:name] %>"><%= file[:name] %></label></li>
            <li class="delete"><a href="<%= url_for delete_file_file_browser_path :file => file[:url] %>" title="Delete this file">delete</a></li>
          </ul>
        </li>
    <% end %>
  </ul>
</div>

app/views/file_browser/_upload_file_form.html.erb
<div id="upload_file_input" style="display: none">
<%= form_tag  'file_browser/file/create',:id=>"new_file",
              :multipart => true do %>
    <input type="hidden" name="post_upload[path]" value="<%= @current_url %>" />
    <h2>Ajouter un fichier</h2>
    <%= label 'post_upload','Choisir fichier:'%>

    <%= file_field 'post_upload', 'datafile' ,:size =>20 %>
    <%= submit_tag "Envoyer" %>
<% end %>
</div>

app/views/file_browser/list.html.erb
<%= javascript_include_tag 'file_browser' %>
<%= stylesheet_link_tag 'list',  :media => 'screen' %>
<input type="button" value="Upload a File" id="toggle_upload_file_input">
<input type="button" value="Create a Directory" id="toggle_create_directory_input">
<%= render :partial => 'upload_file_form' %>
<%= render :partial => 'create_directory_form' %>

<%= render :partial => '_breadcrumb' %>
<%= render :partial => '_file_browser_content' %>

app/views/file_browser/list_for_archive.html.erb
<%= javascript_include_tag 'file_browser' %>
<%= stylesheet_link_tag 'list',  :media => 'screen' %>

<%= render :partial => '_breadcrumb' %>
<%= render :partial => 'archive_content' %>

app/views/file_browser/list_for_piece_jointe.html.erb
<%= javascript_include_tag 'file_browser' %>
<%= stylesheet_link_tag 'list',  :media => 'screen' %>
<h2>Sélectionner Piece-jointe</h2>
<%= render :partial => '_p_j_breadcrumb' %>
<%= render :partial => 'piece_jointe_content' %>

app/views/file_browser/project_files.html.erb
<%= javascript_include_tag 'file_browser' %>
<%= stylesheet_link_tag 'list',  :media => 'screen' %><%=session[:model]%>
<input type="button" value="Upload a File" id="toggle_upload_file_input">
<input type="button" value="Create a Directory" id="toggle_create_directory_input">
<%= render :partial => 'upload_file_form' %>
<%= render :partial => 'create_directory_form' %>

<%= render :partial => '_breadcrumb' %>
<%= render :partial => '_file_browser_content' %>

app/views/file_browser/retrieve_archive.html.erb
<p>Ces enregistrement ont ete recupere du fichier archive</p>
<table>
<%=render_object_or_collection(@comments) unless @comments.empty?%>
</table>

app/views/file_browser/user_files.html.erb
<%= javascript_include_tag 'file_browser' %>
<%= stylesheet_link_tag 'list',  :media => 'screen' %>
<input type="button" value="Upload a File" id="toggle_upload_file_input">
<input type="button" value="Create a Directory" id="toggle_create_directory_input">
<%= render :partial => 'upload_file_form' %>
<%= render :partial => 'create_directory_form' %>

<%= render :partial => '_breadcrumb' %>
<%= render :partial => '_file_browser_content' %>