config/routes.rb
OW::Application.routes.draw do
  resources :service_apres_ventes

  match "/email_box/:id"=>'email_box#show'
  match "/email_box"=>'email_box#index'
  match "/email_box/:id/destroy"=>'email_box#destroy'

  resources :project_actions

  resources :message_boxes do
    resources:comments
  end

  resources :invoices
  match "/invoices/:invoice_id/payments/new"=>'invoices#new_payment' ,:as=>:new_payments
   match "/invoices/:invoice_id/payments/create"=>'invoices#create_payment' ,:as=>:payments
  match "/payments/:payment_id"=>'invoices#destroy_payment',:as=>:payments_destroy
   match '/invoices/:id/facture',:to=>'invoices#create_facture' ,:as=>:facture
  resources :documents

  get "search/new_search"
  get "search/search_options",:as =>:search_options
  get "search/search_result"
  match "search/:model_id/test"=>"search#test"
  match "supports/custom_mail"=>"supports#custom_mail", :as=>:custom_mail
  match "supports/custom_mail_200"=>"supports#custom_mail_200", :as=>:custom_mail_200
  match "supports/send_custom_mail"=>"supports#send_custom_mail", :as=>:send_custom_mail
  match "supports/send_custom_mail_200"=>"supports#send_custom_mail_200", :as=>:send_custom_mail_200
  resources :supports

  resources :comments

  resources :projects do
    resources :invoices
    resources :project_actions

    
  end
  match "project_actions/:id/success_failure"=>"project_actions#success_or_failure", :as=>:success_failure

  root :to => 'home_page#home'

  get "home_page/home"
   get "home_page/test"

  resources :clients do
    resources :projects
  end
  match "message_box/:id/delete_trashed_comments"=>"message_boxes#trashed_comments" ,:as=>:delete_trashed_comments
  match "message_box/:id/archive_comments"=>"message_boxes#archived_comments" ,:as=>:archive_yml_comments
  match "/comments/:id/salvage"=>"comments#salvage_comment",:as=>:salvage_comment
  match "/comments/:id/restore"=>"comments#restore_comment",:as=>:restore_comment
  match "/comments/:id/read"=>"comments#read_comment",:as=>:read_comment
  match "/comments/:id/archive"=>"comments#archive_comment",:as=>:archive_comment
  match "/comments/:id/trash"=>"comments#trash_comment",:as=>:trash_comment
  match "/comments/:id/respond"=>"comments#respond_to_comment",:as=>:respond_comment
  match "/projects/:id/activate_project"=>"projects#activate_project",:as=>:activate_project

  match "/users/:id/activate_user"=>"users#activate_user",:as=>:activate_user
  match "/users/:id/admin"=>"users#admin_user_on_off",:as=>:admin_user
  match "/users/:id/deactivated"=>"users#de_re_activate_user",:as=>:deactivate_user
   match "/users/smtp_settings"=>"users#set_smtp_account_settings",:as=>:set_smtp_account_settings
  match "/users/save_smtp_settings"=>"users#save_smtp_account_settings",:as=>:save_smtp_account_settings
  match "/projects/:id/close_project"=>"projects#close_project",:as=>:close_project
  match "/projects/:id/lost_project"=>"projects#lost_project",:as=>:lost_project
  match "/projects/:id/activate_project"=>"projects#activate_project",:as=>:activate_project
  match "/clients/:id/change_state"=>"clients#change_state",:as=>:client_change_state

  match "/current_user_projects"=>'projects#current_user_projects',:as =>:current_user_projects
  match "/current_user_clients"=>'clients#current_user_clients',:as =>:current_user_clients
  match "/user_clients/:user_id"=>'clients#user_clients',:as =>:user_clients

  get "sessions/new"

  match "files/upload", :to =>'files#upload' ,:as =>'upload_files'
  match "files/post_upload", :to =>'files#post_upload' ,:as =>'post_upload'
  get "files/index"

  get "users/show"
  match "/service_apres_vente/:id/activate_sav"=>"service_apres_ventes#activate_sav",:as=>:activate_sav
  match "/service_apres_vente/:id/close_sav"=>"service_apres_ventes#close_sav",:as=>:close_sav
  match "service_apres_ventes_active", :to =>'service_apres_ventes#index_active' ,:as =>'index_active'
  match "service_apres_ventes_closed", :to =>'service_apres_ventes#index_closed' ,:as =>'index_closed'
  match "service_apres_ventes_sent", :to =>'service_apres_ventes#index_sent' ,:as =>'index_sent'
  match "service_apres_ventes_warranty", :to =>'service_apres_ventes#index_warranty' ,:as =>'index_warranty'
  match "service_apres_ventes_no_warranty", :to =>'service_apres_ventes#index_no_warranty' ,:as =>'index_no_warranty'
  match "service_apres_ventes_planned", :to =>'service_apres_ventes#index_planned' ,:as =>'index_planned'
  match "service_apres_ventes_unplanned", :to =>'service_apres_ventes#index_unplanned' ,:as =>'index_unplanned'
  match "service_apres_ventes/:id/send_form", :to =>'service_apres_ventes#send_sav_form_mail' ,:as =>'send_sav_form_mail'
  match "service_apres_ventes/:id/sav_fiche", :to =>'service_apres_ventes#create_sav_fiche' ,:as =>'create_sav_fiche'
  match 'user_upload', :to => 'users#upload_a_file'
  match 'project_upload', :to => 'projects#upload_a_file'

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/redirect', :to =>'application#redirect_to_last_visited'

  match '/projects/:id/fiche_de_rendez_vous',:to=>'projects#create_rendez_vous_fiche' ,:as=>:fiche_de_rendez_vous
  match '/projects/:id/fiche_de_rendez_vous_mail',:to=>'projects#send_fiche_de_rendez_vous_mail' ,:as=>:fiche_de_rendez_vous_mail
  match '/projects/:id/SAV_form' ,:to=>'projects#send_sav_form_mail',:as=>:send_SAV_form_mail
  match '/project/:id/follow',:to=>'projects#follow_project',:as=>:follow_project
  match '/project/:id/assign',:to=>'projects#assign_project',:as=>:assign_project
  match '/project/:id/project_price',:to=>'projects#set_project_price',:as=>:set_project_price

  resources :user_profiles
  resources :users do
    resource :user_profiles # a verifier

  end

  post "files/post_upload"
  match 'files/download' =>'files#download'

  resources :files
  resources :sessions, :only => [:new, :create, :destroy]
  match '/file_browser/pieces_jointes' => 'file_browser#list_for_piece_jointe', :as => :piece_jointes
   match '/file_browser/set_pieces_jointes' => 'file_browser#set_piece_jointe', :as => :set_piece_jointes
  match '/file_browser' => 'file_browser#list', :as => :file_browser
  match '/user_files' => 'file_browser#user_files', :as => :user_files
   match '/projects/:project_id/project_files' => 'file_browser#project_files', :as => :project_files
  match '/projects/:project_id/file_browser/file/create'  => 'file_browser#create_file',  :as => :create_project_file_file_browser
  match '/file_browser/delete' => 'file_browser#delete', :as => :delete_file_file_browser
  match '/file_browser/dir/create'  => 'file_browser#create_dir',  :as => :create_dir_file_browser
  match '/file_browser/file/create'  => 'file_browser#create_file',  :as => :create_file_file_browser
  match '/file_browser/archive'  => 'file_browser#list_for_archive',  :as => :file_browser_archive
  match '/file_browser/retrieve_archive'  => 'file_browser#retrieve_archive',  :as => :file_browser_retrieve_archive

  get "welcome/index"
  resources :supports, :only => [:new, :create]

end

app/controllers/projects_controller.rb
#encoding: UTF-8
class ProjectsController < ApplicationController
   before_filter :authenticate
   before_filter :user_is_following_project , :only=>[:edit]


  # GET /projects
  # GET /projects.xml
  def current_user_projects
    session[:model_id]=nil
    session[:model]=nil
    @projects=current_user.projects.paginate(:page=>params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  def index
    session[:model_id]=nil
    session[:model]=nil
    if params[:client_id]

    @client=Client.find(params[:client_id])
    @projects =@client.projects.paginate(:page=>params[:page])
    else
     @projects=Project.paginate(:page=>params[:page])
     end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])
    session[:model_id]=@project.id
    session[:model]=@project.class
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @client=Client.find(params[:client_id])
    @project=@client.projects.new(:client_id =>params[:client_id])
    if !@client.contacts.empty?
    @project.contacts.build :contact_data =>@client.contacts.first.contact_data, :genre=>@client.contacts.first.genre,
                            :description=>@client.contacts.first.description
    else
    @project.contacts.build
    end
    if !@client.addresses.empty?
    @project.build_address :street=>@client.addresses.first.street ,:street_number=>@client.addresses.first.street_number,
                            :floor=>@client.addresses.first.floor , :zip=>@client.addresses.first.zip ,
                            :city=>@client.addresses.first.city , :country =>@client.addresses.first.country ,:description =>@client.addresses.first.description
    else
    @project.build_address
    end
    @project.project_components.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit

    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    #@client=Client.find(params[:project][:client_id])
    @project=Project.new(params[:project])
     @project.contacts.each do |contact|
      contact.description=(@project.client.titre+" "+@project.client.surname+" "+@project.client.name) unless !contact.description.blank?
    end

    respond_to do |format|
      if @project.valid?
         define_path
        # current_user.projects<<@project

         @project.activated
         @project.save
         @project.create_home_directory(@public_path)

         @project.client.activate_with_project_creation

        format.html { redirect_to(@project, :notice => 'Projet créé avec succes.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])


    respond_to do |format|
      if @project.update_attributes(params[:project])

        if params[:price_set]=='1'
         if !params[:project][:add_remark].blank?

             @project.remark=@project.remark+"\nRemarque ajoutee: "+params[:project][:add_remark]+"."

         end
         @project.accepted
         @project.save
        end
        format.html { redirect_to(@project, :notice => 'Projet modifié avec succes.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end

    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(client_projects_url(@project.client_id)) }
      format.xml  { head :ok }
    end
  end
   def upload_a_file
      redirect_to :controller =>'files', :action=>'upload'
   end
   def create_rendez_vous_fiche
     @project=Project.find(params[:id])


     respond_to do |format|
        format.html do

          options={:pdf => "my_pdf", # pdf will download as my_pdf.pdf
        :layout => 'pdf', # uses views/layouts/pdf.haml
        :save_only=>true,
         :save_to_file =>File.join(Rails.root.to_s, "/public#{@project.home_directory}/P#{@project.client_id}C#{@project.project_ref}-#{@project.client.surname}.pdf"),
        :show_as_html => params[:debug].present?}

          render_with_wicked_pdf(options)
          render :layout => 'pdf', :pdf_file=>true
        end
        format.xml
        format.pdf do
        render :pdf => "my_pdf", # pdf will download as my_pdf.pdf
        :layout => 'pdf', # uses views/layouts/pdf.haml
        :show_as_html => params[:debug].present? # renders html version if you set debug=true in URL
      end
    end
   end

   def send_fiche_de_rendez_vous_mail
     project=Project.find params[:id]
     project.send_fiche_de_rendez_vous
     redirect_to(request.referer,:notice =>"Fiche de rendez-vous envoyé.")
   end
   def send_sav_form_mail
     project=Project.find params[:id]
     if project.client.contacts.where("genre = 'Email'").any?
     project.send_sav_form
    redirect_to(request.referer,:notice =>"Formulaire de service apres-vente envoyé.")
     else
    redirect_to(request.referer,:notice =>"Aucune adresse Email pour ce client.")
     end
   end
  def activate_project
    @project =Project.find(params[:id])
    @project.activated
    @project.save
    redirect_to request.referer
  end
  def follow_project
    @project=Project.find(params[:id])
    if @project.users.include?(current_user)
      redirect_to(request.referer ,:notice => "Project déja associé a cet utilisateur.")
    else
      current_user.projects<<@project
      current_user.clients<<@project.client  unless current_user.clients.include?(@project.client)
      @project.project_to_offer
      redirect_to(request.referer ,:notice => "Association faite.")
    end
  end

  def assign_project
    @user=User.find(params[:user_id])
    @project=Project.find(params[:id])
     if @project.users.include?(@user)
       redirect_to(request.referer ,:notice => "Project déja assigné a cet utilisateur.")
     else
       @user.projects<<@project
       @user.clients<<@project.client unless @user.clients.include?(@project.client)
       @project.project_to_offer
       redirect_to request.referer ,:notice=>"Le projet #{@project.project_ref_string} est assigné à #{@user.name }."
     end

  end
  def close_project
    notice=""
    @project =Project.find(params[:id])
    if @project.aasm_events_for_current_state.include? :closed
    if @project.closed
    @project.save
    @project.client.close_with_project_end
    notice="Project #{@project.project_ref_string} est fermé."
    @project.user_projects.destroy_all

    else
    notice='Le projet ne satisfait pas aux conditions de clotûre'  
    end
    else
    notice="Transition d'état invalide."  
    end
    redirect_to request.referer, :notice =>notice
  end
   def lost_project
    notice=""
    @project =Project.find(params[:id])
    if @project.aasm_events_for_current_state.include? :lost
    if @project.lost
    @project.save
    @project.user_projects.destroy_all
    @project.client.close_with_project_end
    notice="Project #{@project.project_ref_string} est fermé."

    else
    notice='Le projet ne satisfait pas aux conditions de clotûre'
    end
    else
    notice="Transition d'état invalide."
    end
    redirect_to request.referer, :notice =>notice
  end
  def set_project_price
    @project =Project.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end
private
   def user_is_following_project
     @project = Project.find(params[:id])
     redirect_to(project_path params[:id],:notice =>'Pas authorisé a modifier ce projet') unless( @project.users.include?(current_user)|| current_user.is_admin?)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
  def get_component_type
    ProjectComponent.get_component_type
  end
  def get_component_matter
    ProjectComponent.get_component_matter
  end
  def get_project_type
    Project.get_project_type
  end

  def get_remaining_to_pay project
    if !project.project_price.nil?
      project.invoices.sum(:total_sum)-project.invoices.sum(:remaining_sum)
    else
      0
    end
  end
  def get_already_paid_amount project
    project.invoices.paid_invoices.sum(:total_sum)
  end
  def get_payment_from_unfinished_invoices project
    total=0
    project.invoices.emitted.each do |invoice|
      total=total+invoice.payments.sum(:sum_paid)
    end
   return total
  end
  def get_already_paid_invoices_ref_string project ,invoice
    ref_string=""
    array=project.invoices.paid_invoices.where("invoice_ref <'#{invoice.invoice_ref}'")
    array.each do |facture|
       ref_string=ref_string+" "+facture.invoice_ref
    end
    (63-ref_string.size).times do
      ref_string=ref_string+"&nbsp;"
    end
    return ref_string.html_safe
  end
  def already_associated project
    if project.users.include?(current_user)
      true
    else
      false
    end

  end

end

app/views/projects/_assign_project.html.erb
<div id="assign_project">
  <%= form_tag(assign_project_path(@project) ) do %>
      <%= label_tag(:user_id, "Assigner à :") %>
      <%= select_tag(:user_id,options_for_select(user_name_list)) %>
      <%= submit_tag("Assigner") %>
  <% end %>
</div>

app/views/projects/_project_list.html.erb
 <tr>

    <td><%= redirect_back_to_owner(project) unless project.client==nil %></td>
    <td><%= "C#{project.client_id}P#{project.project_ref}" %></td>
    <td><%= project.aasm_current_state %></td>
    <td><%=I18n.l(project.created_at) %></td>
    <td><%= link_to 'Voir', project %></td>
    <td><%= link_to 'Modifier', edit_project_path(project) %></td>
  

    <td><%= link_to 'Détruire', project, :confirm => 'Etes vous sûres ?', :method => :delete %></td>
  </tr>

app/views/projects/current_user_projects.html.erb
<h1>Liste des projets</h1>

<%= will_paginate :previous_label=>'&larr; Précédent',:next_label=>'Suivant &rarr;' %>
<table>
  <thead>

           <th>Client</th>
           <th>Reference projet</th>
           <th>Etat du projet</th>
           <th>Date de création</th>
           <th></th>
           <th></th>
           <th></th>
   </thead>


<% @projects.each do |project| %>
  <%=render :partial =>'project_list', :object=>project ,:as=>:project %>
<% end %>
</table>
<%= will_paginate :previous_label=>'&larr; Précédent',:next_label=>'Suivant &rarr;' %>
<br />
<%= link_to 'Back' ,user_path(current_user) %>

app/views/projects/edit.html.erb
<h1>Modifier project</h1>

<%= render 'form' %>

<%= link_to 'Voir', @project %> |
<%= link_to 'Retour', client_projects_path(@project.client_id) %>

app/views/projects/new.html.erb
<h1>Nouveau projet</h1>


<%= render 'form' %>
<div class="span-15">
<%= link_to 'Retour', client_path(@project.client_id) %>
</div>

app/views/projects/show.html.erb
<div id="first_content">
  <div class="span-18" style="min-height:50px"><div class="span-10"><h2>Projet: <%= @project.project_ref_string %></h2>
  </div>
  <div class="'span-6">
    <div ><%= render :partial => 'assign_project' unless !current_user.is_admin? %></div>
  </div>
  </div>
<hr>
   <div id="project_info" class="span-8 ">

    <p><b>Client: </b><%=link_to "#{@project.client.titre} #{@project.client.surname} #{@project.client.name}",client_path(@project.client_id) %>
  </p>
     <p><b>Type de projet: </b><%=@project.project_type%></p>
    <p>
      <b>Etat du projet: </b> <%=@project.aasm_current_state%>
    </p>

    <p><b>Creer le: </b><%=I18n.l(@project.created_at)%>
    </p>
    <p><b>Derniere modification: </b><%=I18n.l(@project.updated_at)%></p>

  </div>


<div id="price_info" class="span-8">
<% if !@project.project_price.nil? %>
     <p><b><%= link_to("Informations de facturation:", project_invoices_path(@project))%></b></p>
     <p><b>Prix du projet: </b>
  <%=@project.project_price%>€</p>
      <p><b>Total des paiements: </b>
  <%=get_already_paid_amount(@project)+get_payment_from_unfinished_invoices(@project) %>€</p>
      <p><b>Solde du projet: </b>
  <%#=@project.project_price-get_remaining_to_pay(@project)unless @project.project_price.nil?%>
      <%= project_remaining_to_pay(@project) unless @project.project_price.nil?%>€
      </p><%end %>
  </div>
<hr>

</div>
<% if !@project.remark.blank? %>
 <div  class="span-18">
   <p><b>Remarque:</b><br/>
   <%=new_line_in_text(@project.remark)%></p>
  </div>
<% end %>
<div id="project_price'"></div>

<div class="span-18" id="addresses">
  <h4><b>Adresse du chantier: </b></h4>
<table>
   <%= if !@project.address.nil? then render :partial => "shared/address_show" ,:object=> @project.address ,:as=>:address end%>
</table>
</div>
<div class="span-18">
     <h4><b>Informations Projet: </b></h4> 
   <hr>
  <div class="span-8">
  <b><%=link_to_function("Informations de contact(#{size_collection @project.contacts})"," $('#contacts').toggle();")unless @project.contacts.empty? %></b><br/>
  <b><%=link_to_function("Composants du projet(#{size_collection @project.project_components})"," $('#components').toggle();")unless @project.project_components.empty? %></b><br/>
  <b><%=link_to_function("Fichiers(#{size_collection @project.uploaded_files})"," $('#files_table').toggle();")unless @project.uploaded_files.empty? %></b><br/>
</div>
<% if !@project.project_actions.empty? %>
   <div class="span-8">
      <b><%=link_to("Actions du projet:",project_project_actions_path(@project))%></b>
     <ul style="list-style-type: none;">
       <li><%=link_to_function("En cours(#{size_collection @project.project_actions.open})"," $('#open_action_table').toggle();")unless @project.project_actions.open.empty? %>
</li>
       <li><%=link_to_function("Clotûrées(#{size_collection @project.project_actions.success})"," $('#success_action_table').toggle();")unless @project.project_actions.success.empty? %>
</li>
       <li><%=link_to_function("Echec(#{size_collection @project.project_actions.failure})"," $('#failure_action_table').toggle();")unless @project.project_actions.failure.empty? %>
</li>
     </ul>
   </div>
<%end%>
 </div>
<div class='span-17'id="contacts" style="display:none">
  <hr>
 <h4><b>Informations de contact: </b></h4> 
 <table>
  <thead>

           <th>Description</th>
           <th>Type de contact</th>
           <th>Donnée de contact</th>


         </thead> 
  <%= if !@project.contacts.empty? then render :partial => "shared/contact_list", :collection => @project.contacts ,:as=>:contact end%>
 </table>

</div>



<div class='span-17' id="components" style="display:none">
<hr>
<h4><b>Composants du projet: </b></h4>  
<table>
  <thead>
              
              <th>Type de produit</th>
              <th>Matière</th>
              <th>Nombre de pieces </th>
             <th>Informations complémentaires</th>

              </thead>
  <%= if !@project.project_components.empty? then render :partial => "project_component_list", :collection => @project.project_components,:as=>:project_component end%>
</table>

</div>

<div class="span-17" id="files_table" style="display:none" >
     <hr>
     <h4><b>Fichiers:</b></h4>
    <table class="span-17">

              <thead>
              <th></th>
              <th>Nom du Fichier</th>
              <th>Type de Fichier</th>
              <th>Taille du Fichier</th>
              <th>Propriétaire du Fichier</th>
              <th>SlideShow</th>
              <th></th>

              </thead>

<%=render :partial => "files/show_file", :collection => @project.uploaded_files,
                                                     :as=>:uploaded %>
</table>
</div>


<div class="span-17" id="open_action_table" style="display:none" >
     <hr>
     <h4><b>Actions en cours:</b></h4>

      <table>
        <thead>
            <th>Description</th>
            <th>Type d'action</th>
            <th>Utilisateur</th>
            <th>Résultat</th>
            <th>Etat de l'action</th>
            <th>Reference projet</th>
            <th>Etat du projet</th>
            <th></th>
            <th></th>
          <th></th>
          </thead>



 <%= render :partial => 'project_actions/project_action_list' , :collection => @project.project_actions.open,
                                                     :as=>:project_action %>
</table>
</div>


<div class="span-17" id="success_action_table" style="display:none" >
     <hr>
     <h4><b>Actions Cloturées:</b></h4>

      <table>
        <thead>
            <th>Description</th>
            <th>Type d'action</th>
            <th>Utilisateur</th>
            <th>Résultat</th>
            <th>Etat de l'action</th>
            <th>Reference projet</th>
            <th>Etat du projet</th>
            <th></th>
            <th></th>
          <th></th>
          </thead>



 <%= render :partial => 'project_actions/project_action_list' , :collection => @project.project_actions.success,
                                                     :as=>:project_action %>
</table>
</div>

<div class="span-17" id="failure_action_table" style="display:none" >
     <hr>
     <h4><b>Actions ratées:</b></h4>

      <table>
        <thead>
            <th>Description</th>
            <th>Type d'action</th>
            <th>Utilisateur</th>
            <th>Résultat</th>
            <th>Etat de l'action</th>
            <th>Reference projet</th>
            <th>Etat du projet</th>
            <th></th>
            <th></th>
          <th></th>
          </thead>
        


 <%= render :partial => 'project_actions/project_action_list' , :collection => @project.project_actions.failure,
                                                     :as=>:project_action %>
</table>
</div>



<% content_for :sidebar do %>
    
    <div id="vertmenu">
      <ul>


     <li>
<%= link_to'Explorer les fichiers' ,project_files_path(@project),:tabindex=>"1" %>
       </li>
        <li>
         <%=  link_to 'Uploader un fichier', upload_files_path(:format=>:js),:remote=>true,:tabindex=>'2'%>
        </li>
       <%# <li>
       = link_to'Uploader' ,:controller =>'projects' ,:action=>'upload_a_file',:tabindex=>'2'</li>%>
        <% if !@project.message_box.nil?%>
         <li>
    <%= (link_to 'Messages  ',message_box_path(@project.message_box.id ),:tabindex=>'3') %>
      </li>
        <% end %>
        <li>
<%= link_to('Fiche de RDV' ,fiche_de_rendez_vous_path(@project),:target=>'_blank',:tabindex=>'4')%>
       </li>
<li>
<%= link_to'Fiche de RDV en pdf ' ,fiche_de_rendez_vous_path(@project,:format=>'pdf'),:tabindex=>'5'%>
       </li>
        <li>
<%= link_to'Fiche de RDV par mail ' ,fiche_de_rendez_vous_mail_path(@project),:tabindex=>'6'%>
       </li>
        <li>
<%= link_to'Formulaire SAV par mail ' ,send_SAV_form_mail_path(@project),:tabindex=>'7'%>
       </li>
<%if !@project.project_price.nil? %>
<li>
<%= link_to'Factures du projet' , project_invoices_path(@project) %>
       </li>
<%end%>
<%if @project.aasm_current_state ==:placement%>
  <li>
<%= link_to'Fermer projet' , close_project_path(@project),:tabindex=>'10'%>
       </li>
<%end%>
<%if @project.project_price.nil? && @project.aasm_current_state!=:project_lost %>
        <li>
<%= link_to'Projet perdu' , lost_project_path(@project),:tabindex=>'10'%>
       </li>
<%end%>

       <% if !already_associated(@project) %>
        <li>
      <%= (link_to 'Suivre projet ',follow_project_path(@project),:tabindex=>'11')  %>
      </li>
        <%end%>    
       <% if  @project.aasm_current_state == :offer %>
         <%#<li>
           <%= link_to 'Projet accepter ',set_project_price_path(@project),:tabindex=>'12'
      </li>%>
         <li>
      <%= link_to 'Projet accepté ',set_project_price_path(@project,:format=>:js),:remote=>true,:tabindex=>'12' %>
      </li>
        <%end%>
         <li>
      <%= link_to 'Nouvelle action ',new_project_project_action_path(@project) %>
      </li>
        <li><%= link_to 'Modifier', edit_project_path(@project)  %>
        </li>
        <li><%= link_to 'Retour', client_path(@project.client_id) %></li>
      </ul>
    </div>



     <div id= "options_link"><%#= link_to 'Options', upload_files_path(:format=>:js),:remote=>true %></div>


<% end%>