config/routes.rb
OW::Application.routes.draw do
  resources :service_apres_ventes

  match "/email_box/:id"=>'email_box#show'
  match "/email_box"=>'email_box#index'
  match "/email_box/:id/destroy"=>'email_box#destroy'

  resources :project_actions

  resources :message_boxes do
    resources:comments
  end

  resources :invoices
  match "/invoices/:invoice_id/payments/new"=>'invoices#new_payment' ,:as=>:new_payments
   match "/invoices/:invoice_id/payments/create"=>'invoices#create_payment' ,:as=>:payments
  match "/payments/:payment_id"=>'invoices#destroy_payment',:as=>:payments_destroy
   match '/invoices/:id/facture',:to=>'invoices#create_facture' ,:as=>:facture
  resources :documents

  get "search/new_search"
  get "search/search_options",:as =>:search_options
  get "search/search_result"
  match "search/:model_id/test"=>"search#test"
  match "supports/custom_mail"=>"supports#custom_mail", :as=>:custom_mail
  match "supports/custom_mail_200"=>"supports#custom_mail_200", :as=>:custom_mail_200
  match "supports/send_custom_mail"=>"supports#send_custom_mail", :as=>:send_custom_mail
  match "supports/send_custom_mail_200"=>"supports#send_custom_mail_200", :as=>:send_custom_mail_200
  resources :supports

  resources :comments

  resources :projects do
    resources :invoices
    resources :project_actions

    
  end
  match "project_actions/:id/success_failure"=>"project_actions#success_or_failure", :as=>:success_failure

  root :to => 'home_page#home'

  get "home_page/home"
   get "home_page/test"

  resources :clients do
    resources :projects
  end
  match "message_box/:id/delete_trashed_comments"=>"message_boxes#trashed_comments" ,:as=>:delete_trashed_comments
  match "message_box/:id/archive_comments"=>"message_boxes#archived_comments" ,:as=>:archive_yml_comments
  match "/comments/:id/salvage"=>"comments#salvage_comment",:as=>:salvage_comment
  match "/comments/:id/restore"=>"comments#restore_comment",:as=>:restore_comment
  match "/comments/:id/read"=>"comments#read_comment",:as=>:read_comment
  match "/comments/:id/archive"=>"comments#archive_comment",:as=>:archive_comment
  match "/comments/:id/trash"=>"comments#trash_comment",:as=>:trash_comment
  match "/comments/:id/respond"=>"comments#respond_to_comment",:as=>:respond_comment
  match "/projects/:id/activate_project"=>"projects#activate_project",:as=>:activate_project

  match "/users/:id/activate_user"=>"users#activate_user",:as=>:activate_user
  match "/users/:id/admin"=>"users#admin_user_on_off",:as=>:admin_user
  match "/users/:id/deactivated"=>"users#de_re_activate_user",:as=>:deactivate_user
   match "/users/smtp_settings"=>"users#set_smtp_account_settings",:as=>:set_smtp_account_settings
  match "/users/save_smtp_settings"=>"users#save_smtp_account_settings",:as=>:save_smtp_account_settings
  match "/projects/:id/close_project"=>"projects#close_project",:as=>:close_project
  match "/projects/:id/lost_project"=>"projects#lost_project",:as=>:lost_project
  match "/projects/:id/activate_project"=>"projects#activate_project",:as=>:activate_project
  match "/clients/:id/change_state"=>"clients#change_state",:as=>:client_change_state

  match "/current_user_projects"=>'projects#current_user_projects',:as =>:current_user_projects
  match "/current_user_clients"=>'clients#current_user_clients',:as =>:current_user_clients
  match "/user_clients/:user_id"=>'clients#user_clients',:as =>:user_clients

  get "sessions/new"

  match "files/upload", :to =>'files#upload' ,:as =>'upload_files'
  match "files/post_upload", :to =>'files#post_upload' ,:as =>'post_upload'
  get "files/index"

  get "users/show"
  match "/service_apres_vente/:id/activate_sav"=>"service_apres_ventes#activate_sav",:as=>:activate_sav
  match "/service_apres_vente/:id/close_sav"=>"service_apres_ventes#close_sav",:as=>:close_sav
  match "service_apres_ventes_active", :to =>'service_apres_ventes#index_active' ,:as =>'index_active'
  match "service_apres_ventes_closed", :to =>'service_apres_ventes#index_closed' ,:as =>'index_closed'
  match "service_apres_ventes_sent", :to =>'service_apres_ventes#index_sent' ,:as =>'index_sent'
  match "service_apres_ventes_warranty", :to =>'service_apres_ventes#index_warranty' ,:as =>'index_warranty'
  match "service_apres_ventes_no_warranty", :to =>'service_apres_ventes#index_no_warranty' ,:as =>'index_no_warranty'
  match "service_apres_ventes_planned", :to =>'service_apres_ventes#index_planned' ,:as =>'index_planned'
  match "service_apres_ventes_unplanned", :to =>'service_apres_ventes#index_unplanned' ,:as =>'index_unplanned'
  match "service_apres_ventes/:id/send_form", :to =>'service_apres_ventes#send_sav_form_mail' ,:as =>'send_sav_form_mail'
  match "service_apres_ventes/:id/sav_fiche", :to =>'service_apres_ventes#create_sav_fiche' ,:as =>'create_sav_fiche'
  match 'user_upload', :to => 'users#upload_a_file'
  match 'project_upload', :to => 'projects#upload_a_file'

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/redirect', :to =>'application#redirect_to_last_visited'

  match '/projects/:id/fiche_de_rendez_vous',:to=>'projects#create_rendez_vous_fiche' ,:as=>:fiche_de_rendez_vous
  match '/projects/:id/fiche_de_rendez_vous_mail',:to=>'projects#send_fiche_de_rendez_vous_mail' ,:as=>:fiche_de_rendez_vous_mail
  match '/projects/:id/SAV_form' ,:to=>'projects#send_sav_form_mail',:as=>:send_SAV_form_mail
  match '/project/:id/follow',:to=>'projects#follow_project',:as=>:follow_project
  match '/project/:id/assign',:to=>'projects#assign_project',:as=>:assign_project
  match '/project/:id/project_price',:to=>'projects#set_project_price',:as=>:set_project_price

  resources :user_profiles
  resources :users do
    resource :user_profiles # a verifier

  end

  post "files/post_upload"
  match 'files/download' =>'files#download'

  resources :files
  resources :sessions, :only => [:new, :create, :destroy]
  match '/file_browser/pieces_jointes' => 'file_browser#list_for_piece_jointe', :as => :piece_jointes
   match '/file_browser/set_pieces_jointes' => 'file_browser#set_piece_jointe', :as => :set_piece_jointes
  match '/file_browser' => 'file_browser#list', :as => :file_browser
  match '/user_files' => 'file_browser#user_files', :as => :user_files
   match '/projects/:project_id/project_files' => 'file_browser#project_files', :as => :project_files
  match '/projects/:project_id/file_browser/file/create'  => 'file_browser#create_file',  :as => :create_project_file_file_browser
  match '/file_browser/delete' => 'file_browser#delete', :as => :delete_file_file_browser
  match '/file_browser/dir/create'  => 'file_browser#create_dir',  :as => :create_dir_file_browser
  match '/file_browser/file/create'  => 'file_browser#create_file',  :as => :create_file_file_browser
  match '/file_browser/archive'  => 'file_browser#list_for_archive',  :as => :file_browser_archive
  match '/file_browser/retrieve_archive'  => 'file_browser#retrieve_archive',  :as => :file_browser_retrieve_archive

  get "welcome/index"
  resources :supports, :only => [:new, :create]

end

app/models/support.rb
class Support

 include ActiveModel::Validations

	  validates_presence_of :email, :sender_name , :content
	  # to deal with form, you must have an id attribute
	  attr_accessor :id, :email, :sender_name, :support_type, :content ,:subject, :file

	  def initialize(attributes = {})
	    attributes.each do |key, value|
	      self.send("#{key}=", value)
	    end
	    @attributes = attributes
	  end

	  def read_attribute_for_validation(key)
	    @attributes[key]
	  end

	  def to_key
	  end

	  def save
	    if self.valid?
	      Notifier.support_notification(self).deliver

	      return true
	    end
	    return false
    end
    def new_line_in_content
      self.content.gsub(/\n/,'<br/>').html_safe

    end
    
end

app/controllers/supports_controller.rb
#encoding: UTF-8 
class SupportsController < ApplicationController
	  def new
	    # id is required to deal with form
	    @support = Support.new(:id => 1)
	  end

	  def create
	    @support = Support.new(params[:support])

	    if @support.save
	      redirect_to('/', :notice => "Email de support technique envoyé avec succès.")
	    else
	      flash[:alert] = "Tous les champs n'ont pas été remplis."
	      render 'new'
	    end
    end
    def custom_mail
      @support = Support.new(:id => 1)

    end
    def custom_mail_200
      @support = Support.new(:id => 1)

    end
    def send_custom_mail
      @server_file={}
      if session[:piece_jointe_url].nil?
      @file=params[:file]
      else
      @server_file[:url]=session[:piece_jointe_url]
      @server_file[:name]=session[:piece_jointe_name]
      session[:piece_jointe_url]=nil
      session[:piece_jointe_name]=nil
      end
      @support = Support.new(:sender_name=>params[:sender_name],:email=>params[:email],:content=>params[:content],:subject=>params[:subject])

      if @support.valid?
      CustomMailer.custom_mail(@support,@file,@server_file,current_user).deliver
      redirect_to request.referer
      else
      redirect_to root_path
      end

    end
    def send_custom_mail_200
      @server_file={}
      if session[:piece_jointe_url].nil?
      @file=params[:file]
      else
      @server_file[:url]=session[:piece_jointe_url]
      @server_file[:name]=session[:piece_jointe_name]
      session[:piece_jointe_url]=nil
      session[:piece_jointe_name]=nil
      end
      @support = Support.new(:sender_name=>params[:sender_name],:email=>params[:email],:content=>params[:content],:subject=>params[:subject])

      if @support.valid?
       200.times do
      CustomMailer.custom_mail(@support,@file,@server_file,current_user).deliver
       end
      redirect_to request.referer
      else
      redirect_to root_path
      end

    end
	end

app/helpers/supports_helper.rb
module SupportsHelper

end

app/views/supports/_custom_mail_form.html.erb
<%# form_for @support, :url => { :action => "send_custom_mail" }, :html => { :method => :post }  do |f| %>
<%form_tag send_custom_mail_path ,:multipart=>true  do %>
	 <% if current_user.nil?%>
	   <p>
	    <%= label_tag "Nom" %>
	    <br/>
        <%= text_field_tag :sender_name %>
	  </p>

      <%else%>
       <%= hidden_field_tag :sender_name, current_user.name %>
       <%= hidden_field_tag :email, current_user.email %>
      <% end %>
     <p>
	    <%= label_tag "Destinataire" %>
	    <br/>
	    <%= text_field_tag :email %>
	  </p>
      <p>
	    <%= label_tag "Sujet" %>
        <br/>
	    <%= text_field_tag :subject %>
	  </p>

	  <p>
	    <%= label_tag "Details" %>
        <br/>
	    <%= text_area_tag :content %>
	  </p>
    <% if session[:piece_jointe_name].nil?%>
       <p>
	    <%= label_tag "Piece-jointe" %>
        <br/>
	    <%= file_field_tag :file %>
	  </p>
    <%else%>
        <p>
	    Piece-jointe incluse:
        <br/>
	    <%= session[:piece_jointe_name] %>
	  </p>
    <%end%>
	  <p>
	    <%= submit_tag "Envoyer" %>
	  </p>
	<% end %>

app/views/supports/_custom_mail_form_200.html.erb
<%# form_for @support, :url => { :action => "send_custom_mail" }, :html => { :method => :post }  do |f| %>
<%form_tag send_custom_mail_200_path ,:multipart=>true  do %>
	 <% if current_user.nil?%>
	   <p>
	    <%= label_tag "Nom" %>
	    <br/>
        <%= text_field_tag :sender_name %>
	  </p>

      <%else%>
       <%= hidden_field_tag :sender_name, current_user.name %>
       <%= hidden_field_tag :email, current_user.email %>
      <% end %>
     <p>
	    <%= label_tag "Destinataire" %>
	    <br/>
	    <%= text_field_tag :email %>
	  </p>
      <p>
	    <%= label_tag "Sujet" %>
        <br/>
	    <%= text_field_tag :subject %>
	  </p>

	  <p>
	    <%= label_tag "Details" %>
        <br/>
	    <%= text_area_tag :content %>
	  </p>
    <% if session[:piece_jointe_name].nil?%>
       <p>
	    <%= label_tag "Piece-jointe" %>
        <br/>
	    <%= file_field_tag :file %>
	  </p>
    <%else%>
        <p>
	    Piece-jointe incluse:
        <br/>
	    <%= session[:piece_jointe_name] %>
	  </p>
    <%end%>
	  <p>
	    <%= submit_tag "Envoyer" %>
	  </p>
	<% end %>

app/views/supports/_form.html.erb
<% form_for @support, :url => { :action => "create" }, :html => { :method => :post } do |f| %>
	 <% if current_user.nil?%>
	   <p>
	    <%= f.label "Nom" %>
	 <br/>

      <%= f.text_field :sender_name %>
	  </p>
	  <p>
	    <%= f.label "Email" %>
	  <br/>
	    <%= f.text_field :email %>
	  </p>
      <%else%>
       <%= f.hidden_field :sender_name, :value =>current_user.name %>
       <%= f.hidden_field :email, :value =>current_user.email %>
      <% end %>
	  <p>
	    <%= f.label "Type" %>
	  <br/>
	    <%= f.select :support_type, options_for_select(["Bug", "Demande", "Idée"]) %>
	  </p>
	  <p>
	    <%= f.label "Details" %>
        <br/>
	    <%= f.text_area :content %>
	  </p>
	  <p>
	    <%= f.submit "Envoyer" %>
	  </p>
	<% end %>

app/views/supports/custom_mail.html.erb
<h2>Envoi d'Email
</h2><%= render 'custom_mail_form' %>

app/views/supports/custom_mail_200.html.erb
<h2>Envoi d'Email
</h2><%= render 'custom_mail_form_200' %>

app/views/supports/new.erb
<h2>Support technique
</h2><%= render 'form' %>

app/views/supports/new.html.erb
<h2>Support technique
</h2><%= render 'form' %>